# Generated by Django 5.2.7 on 2025-11-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_token",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите телеграмм chat-id",
                max_length=150,
                null=True,
                verbose_name="Телеграмм chat-id",
            ),
        ),
    ]
