# Generated by Django 5.2.7 on 2025-10-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_complete",
            field=models.DurationField(
                help_text="Укажите время на выполнение в секундах", verbose_name="Время на выполнение в секундах"
            ),
        ),
    ]
