# Generated by Django 5.2.7 on 2025-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0003_alter_habit_time_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1, help_text="Укажите периодичность", verbose_name="Периодичность"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Укажите вознаграждение",
                max_length=150,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
