# Generated by Django 5.2.7 on 2025-10-31 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0004_alter_habit_periodicity_alter_habit_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="associated_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связанную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habit_tracker.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
